name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test with env $BT_ENVIRONMENT
      run: |
        npm install
        npm test
      env:
        CI: true
        BT_ENVIRONMENT: Sandbox
        BT_MERCHANT_ID: ${{secrets.BT_MERCHANT_ID}}
        BT_PUBLIC_KEY: ${{secrets.BT_PUBLIC_KEY}}
        BT_PRIVATE_KEY: ${{secrets.BT_PRIVATE_KEY}} 
